### ISSUE TITLE
Font is 1 size larger than the original rubjo/victor-mono

### ISSUE THREAD

**Issue by acid-bong** [rubjo/victor-mono-font#8]
Tried both 1.560 and .562, both are pretty large in the terminal: size 10 looks like original size 11, size 9 looks like OG 10 and so on. Both st and Alacritty, and the dwm statusbar reflect this. No difference in Firefox tho.

Is this a requirement for Google or some miscalculation in the build process?

**Comment by rubjo** [comment]
In the process of making the font ready for Google Fonts, several adjustments for the font metrics and settings needed to be made to satisfy their tests to pass and have the font be approved for GF inclusion. This probably leads to the GF version looking slightly different from the one in the main repo. I might backport most or all these changes to the main repo at some point.

**Comment by acid-bong** [comment]
Including the size difference? I already see improvements in [handling line height](https://github.com/ryanoasis/nerd-fonts/issues/1317), for which big kudos, but other fonts' (Liberation Mono, Iosevka) glyphs have roughly the same height (within one font size) as the OG Victor Mono

**Comment by rubjo** [comment]
If I ever get around to merging and unifying the differences between the two variants, I might look into how future versions could preserve the original size - as for now, I guess the best option is to decrease the font size by 1?

**Comment by acid-bong** [comment]
As for now with this font -- yes, that's what I'm doing. Anyway, best luck and cheers

**Comment by Finii** [comment]
The outlines are 100% the same, but the EM size changed.
EM is used to define how font-point-size translates to outline-coordinates.

![image](https://github.com/rubjo/victor-mono-font/assets/16012374/72584f1b-a4d6-4681-ad49-9acfd9f3a6d5)

All the other metrics are identical or fixed, and the gap has been dropped:

![image](https://github.com/rubjo/victor-mono-font/assets/16012374/52faa05b-6d0e-4075-b138-f14868588462)

So the singe change is the EM change. The old value of 1100 is 'unusual' and should trigger a warning with GF, but should not be an error. It is independent on all other metrics (changes).

Do GF really flag 1100 as error?

_Edit: GRR, the top image shows 1.562 **left** while in the bottom image 1.562 is **right**, sorry to confuse you_
_Edit: Exchanged top (fontforge) image, **left** is now always 1.540_

**Comment by rubjo** [comment]
Looking at the spec, it was probably just a warning, yes.

**Comment by Finii** [comment]
Well, if you export `ttf` and `otf` with the same EM, you will get a warning either here or there, because they have conflicting 'customary values' ;-)
I guess these old expectations of EM value are obsolete nowadays anyway. I remember a discussion on some font forum, maybe I can find it.

![image](https://github.com/rubjo/victor-mono-font/assets/16012374/5d48e215-364c-450a-befe-ea51ce72aa60)
_Pic taken of my "Fonts & Encodings" by Haralamnous_

And Victor Gaultney writes [here](http://silnrsi.github.io/FDBP/en-US/Design_Metrics.html#special-upm-values):

![image](https://github.com/rubjo/victor-mono-font/assets/16012374/6b0e211e-e2b0-4cac-a386-5ac84f8947cb)

If you change the EM and want to keep the look the same you need to scale all glyphs. I know that `fontforge` can do that, never needed to do that with Glyphs (and I do not even know what you use ;-)

![image](https://github.com/rubjo/victor-mono-font/assets/16012374/ff29efb1-1d1e-4950-abfa-059b746fa4d7)

**Comment by Finii** [comment]
https://forum.glyphsapp.com/t/how-to-change-the-upm-and-scale-proportionally-contours-and-metrics-and-kerning/21000/3

**Comment by rubjo** [comment]
Thanks, I'm trying this now and hoping that will solve the size difference at least.

**Comment by acid-bong** [comment]
Now 1.563 is back to its original size, thanks :+1:
